### ISSUE TITLE
ReferenceError: invalids is not defined

### ISSUE THREAD

**Issue by dmnsgn** [super-ienien/percent-round#1]
Sorry not entirely sure what input triggered the error, but in any case the belows object `invalids` is undefined.

https://github.com/super-ienien/percent-round/blob/a722c2591bf3dce4f3eade06a95de4a9cd640516/index.js#L90

**Comment by dmnsgn** [comment]
`moment(["20", "30", "40", "30"])` passing string instead of number is actually the reason.

**Comment by super-ienien** [comment]
Hi thanks ! I will fix it

**Comment by super-ienien** [comment]
Fixed in v2.0.0
